CREATE TABLE IF NOT EXISTS booking(
  id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL UNIQUE,
  check_in DATETIME NOT NULL,
  check_out DATETIME NOT NULL,
  total_price DECIMAL(10,2) NOT NULL,
  user_id BIGINT,
  room_id   BIGINT,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  FOREIGN KEY (room_id) REFERENCES room(id) ON DELETE  CASCADE
);