CREATE TABLE IF NOT EXISTS user
(
id BIGINT PRIMARY KEY AUTO_INCREMENT  NOT NULL UNIQUE,
first_name VARCHAR (45) NOT NULL,
surname VARCHAR (45) NOT NULL,
password VARCHAR (45) NOT NULL,
card_number VARCHAR (45),
address_id BIGINT,
FOREIGN KEY (address_id) REFERENCES address(id) ON DELETE CASCADE
);
